(function(){
  'use strict';
  const $=id=>document.getElementById(id),config=window.CASINO_SUPABASE_CONFIG||{};let client,rooms=[],players=[],withdrawals=[],notifications=[];
  const labels={blackjack:'Blackjack',roulette:'Ruleta','tres-y-dos':'Tres y Dos',domino:'Dominó',poker:'Póker',waiting:'Esperando',active:'Activa',closed:'Cerrada'};
  function message(text){$('adminMessage').textContent=text}
  function loadLibrary(){if(window.supabase?.createClient)return Promise.resolve();return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';script.onload=resolve;script.onerror=()=>reject(new Error('No se pudo cargar Supabase.'));document.head.appendChild(script)})}
  async function ensureClient(){if(client)return client;if(!config.url||!config.publishableKey)throw new Error('Supabase no está configurado.');await loadLibrary();client=window.supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});const {data:{session}}=await client.auth.getSession();if(!session){const {error}=await client.auth.signInAnonymously();if(error)throw error}return client}
  async function rpc(name,params){await ensureClient();const {data,error}=await client.rpc(name,params);if(error)throw error;return data}
  const format=value=>Number(value||0).toLocaleString('es-ES'),date=value=>new Date(value).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'});
  function cell(row,text,sub=''){const td=document.createElement('td'),strong=document.createElement('strong');strong.textContent=text;td.append(strong);if(sub){const small=document.createElement('small');small.textContent=sub;td.append(small)}row.append(td)}
  function renderSummary(summary){const cards=[['JUGADORES',summary.players,'perfiles'],['PUNTOS',summary.total_points,'acumulados'],['SALAS',summary.rooms,'creadas'],['ESPERANDO',summary.waiting_rooms,'salas'],['ACTIVAS',summary.active_rooms,'salas'],['CONECTADOS',summary.connected_members,'miembros']];$('summaryCards').replaceChildren(...cards.map(([label,value,sub])=>{const card=document.createElement('article');card.className='summary-card';const span=document.createElement('span'),b=document.createElement('b'),small=document.createElement('small');span.textContent=label;b.textContent=format(value);small.textContent=sub;card.append(span,b,small);return card}))}
  function renderRooms(){const filter=$('roomFilter').value,items=rooms.filter(room=>!filter||room.status===filter),body=$('roomsTable');if(!items.length){const row=document.createElement('tr'),td=document.createElement('td');td.colSpan=7;td.className='empty-row';td.textContent='No hay salas con este filtro.';row.append(td);body.replaceChildren(row);return}body.replaceChildren(...items.map(room=>{const row=document.createElement('tr');cell(row,room.invite_code,room.room_id);cell(row,labels[room.game_type]||room.game_type);const status=document.createElement('td'),pill=document.createElement('span');pill.className=`status-pill ${room.status}`;pill.textContent=(labels[room.status]||room.status)+(room.is_locked?' · BLOQUEADA':'');status.append(pill);row.append(status);cell(row,room.host_name,room.host_mode==='moderator'?'Solo moderador':'Jugador y moderador');cell(row,String(room.member_count));cell(row,date(room.created_at));const action=document.createElement('td'),button=document.createElement('button');button.className='outline-btn';button.textContent='ADMINISTRAR';button.onclick=()=>showRoomAdmin(room);action.append(button);row.append(action);return row}))}
  function renderPlayers(){const query=$('playerSearch').value.trim().toLowerCase(),items=players.filter(player=>!query||player.display_name.toLowerCase().includes(query)||player.player_code.toLowerCase().includes(query)),body=$('playersTable');if(!items.length){const row=document.createElement('tr'),td=document.createElement('td');td.colSpan=6;td.className='empty-row';td.textContent='No hay jugadores con este filtro.';row.append(td);body.replaceChildren(row);return}body.replaceChildren(...items.map(player=>{const row=document.createElement('tr');row.title='Abrir historial del jugador';row.style.cursor='pointer';row.onclick=()=>showPlayerActivity(player.player_code);cell(row,player.display_name,player.player_code);cell(row,format(player.points));cell(row,player.room_code||'Sin sala',player.game_type?labels[player.game_type]||player.game_type:'');cell(row,player.room_credits===null?'—':format(player.room_credits));cell(row,date(player.created_at));const actions=document.createElement('td'),edit=document.createElement('button'),history=document.createElement('button');edit.className='primary-btn';edit.textContent='EDITAR PUNTOS';edit.onclick=event=>{event.stopPropagation();editPlayerPoints(player)};history.className='outline-btn';history.textContent='HISTORIAL';history.onclick=event=>{event.stopPropagation();showPlayerActivity(player.player_code)};actions.append(edit,history);row.append(actions);return row}))}
  function renderWithdrawals(){const filter=$('withdrawalFilter').value,items=withdrawals.filter(x=>!filter||x.status===filter),body=$('withdrawalsTable');if(!items.length){const row=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.className='empty-row';td.textContent='No hay solicitudes.';row.append(td);body.replaceChildren(row);return}body.replaceChildren(...items.map(x=>{const row=document.createElement('tr');cell(row,x.display_name,x.player_code);cell(row,format(x.requested_points));cell(row,x.status);cell(row,date(x.created_at));const actions=document.createElement('td');if(x.status==='pending'){for(const decision of ['approved','rejected']){const button=document.createElement('button');button.className='outline-btn';button.textContent=decision==='approved'?'MARCAR ENTREGADO':'RECHAZAR';button.onclick=()=>decideWithdrawal(x.request_id,decision);actions.append(button)}}else actions.textContent=x.admin_note||'—';row.append(actions);return row}))}
  function renderNotifications(){const box=$('adminNotifications');if(!notifications.length){const p=document.createElement('p');p.className='empty-row';p.textContent='No hay avisos.';box.replaceChildren(p);return}box.replaceChildren(...notifications.map(x=>{const a=document.createElement('article');a.className=`activity-item ${x.is_read?'':'unread'}`;const d=document.createElement('div'),b=document.createElement('b'),small=document.createElement('small');b.textContent=x.title;small.textContent=`${x.message} · ${date(x.created_at)}`;d.append(b,small);a.append(d);if(!x.is_read){const button=document.createElement('button');button.textContent='LEÍDA';button.onclick=()=>rpc('mark_casino_notification_read',{p_notification_id:x.id}).then(loadDashboard);a.append(button)}return a}))}
  async function decideWithdrawal(id,decision){const note=prompt(decision==='approved'?'Nota opcional de entrega:':'Motivo opcional del rechazo:','');if(note===null)return;await rpc('admin_decide_withdrawal',{p_request_id:id,p_decision:decision,p_admin_note:note});await loadDashboard()}
  function showRoomAdmin(room){$('roomAdminTitle').textContent=`${labels[room.game_type]||room.game_type} · ${room.invite_code}`;const actions=$('roomAdminActions'),lock=document.createElement('button'),end=document.createElement('button');lock.className='outline-btn';lock.textContent=room.is_locked?'DESBLOQUEAR SALA':'BLOQUEAR SALA';lock.disabled=room.status==='closed';lock.onclick=()=>manageRoom(room,room.is_locked?'unlock':'lock');end.className='danger-btn';end.textContent='TERMINAR SALA POR COMPLETO';end.disabled=room.status==='closed';end.onclick=()=>manageRoom(room,'terminate');actions.replaceChildren(lock,end);const members=players.filter(player=>player.room_code===room.invite_code),box=$('roomAdminMembers');if(!members.length){const p=document.createElement('p');p.className='empty-row';p.textContent='Esta sala no tiene jugadores conectados.';box.replaceChildren(p)}else box.replaceChildren(...members.map(player=>{const item=document.createElement('article'),info=document.createElement('div'),name=document.createElement('b'),detail=document.createElement('small'),kick=document.createElement('button');item.className='activity-item';name.textContent=player.display_name;detail.textContent=`${player.player_code} · ${format(player.room_credits)} puntos`;info.append(name,detail);kick.className='danger-btn';kick.textContent='EXPULSAR';kick.onclick=()=>kickPlayer(room,player);item.append(info,kick);return item}));$('roomAdminPanel').hidden=false;$('roomAdminPanel').scrollIntoView({behavior:'smooth'})}
  async function manageRoom(room,action){const text=action==='terminate'?'Esta acción cerrará la sala para todos los jugadores.':action==='lock'?'Nadie nuevo podrá entrar mientras esté bloqueada.':'La sala volverá a aceptar jugadores.';if(!confirm(text+' ¿Continuar?'))return;try{await rpc('admin_manage_casino_room',{p_room_id:room.room_id,p_action:action});await loadDashboard()}catch(error){alert(error.message||String(error))}}
  async function kickPlayer(room,player){if(!confirm(`¿Expulsar a ${player.display_name} de la sala ${room.invite_code}?`))return;try{await rpc('admin_kick_casino_room_member',{p_room_id:room.room_id,p_player_code:player.player_code});await loadDashboard();const updated=rooms.find(item=>item.room_id===room.room_id);if(updated)showRoomAdmin(updated)}catch(error){alert(error.message||String(error))}}
  async function editPlayerPoints(player){const value=prompt(`Nuevo saldo total para ${player.display_name}:`,String(player.points));if(value===null)return;const points=Number(value);if(!Number.isInteger(points)||points<0||points>1000000)return alert('Escribe un número entero entre 0 y 1,000,000.');const reason=prompt('Motivo del cambio (quedará en el historial):','Puntos otorgados por administración');if(reason===null)return;try{await rpc('admin_set_player_points',{p_player_code:player.player_code,p_points:points,p_reason:reason});await loadDashboard();await showPlayerActivity(player.player_code)}catch(error){alert(error.message||String(error))}}
  async function showPlayerActivity(code){const data=await rpc('admin_player_activity',{p_player_code:code}),box=$('playerActivity');$('activityPlayerName').textContent=`${data.profile.display_name} · ${data.profile.player_code}`;const entries=[...(data.transactions||[]).map(x=>({date:x.created_at,title:x.description,text:`${x.amount>0?'+':''}${format(x.amount)} · saldo ${format(x.balance_after)}`})),...(data.games||[]).map(x=>({date:x.created_at,title:`${x.game_type} · ${x.result}`,text:`${x.points_delta>0?'+':''}${format(x.points_delta)} puntos`})),...(data.withdrawals||[]).map(x=>({date:x.created_at,title:`Retiro ${x.status}`,text:`${format(x.requested_points)} puntos`}))].sort((a,b)=>new Date(b.date)-new Date(a.date));if(!entries.length){const p=document.createElement('p');p.className='empty-row';p.textContent='Este jugador todavía no tiene actividad registrada.';box.replaceChildren(p)}else box.replaceChildren(...entries.map(x=>{const a=document.createElement('article');a.className='activity-item';const d=document.createElement('div'),b=document.createElement('b'),s=document.createElement('small');b.textContent=x.title;s.textContent=`${x.text} · ${date(x.date)}`;d.append(b,s);a.append(d);return a}));$('playerActivityPanel').hidden=false;$('playerActivityPanel').scrollIntoView({behavior:'smooth'})}
  async function loadDashboard(){message('Verificando acceso…');const [summary,roomData,playerData,withdrawalData,noteData]=await Promise.all([rpc('admin_casino_summary'),rpc('admin_list_casino_rooms'),rpc('admin_list_casino_players'),rpc('admin_list_withdrawal_requests'),rpc('list_my_casino_notifications')]);rooms=roomData||[];players=playerData||[];withdrawals=withdrawalData||[];notifications=noteData||[];renderSummary(summary);renderRooms();renderPlayers();renderWithdrawals();renderNotifications();$('adminLogin').hidden=true;$('adminDashboard').hidden=false;message('')}
  $('adminLoginForm').onsubmit=event=>{event.preventDefault();message('Recuperando perfil…');const values=new FormData(event.currentTarget);ensureClient().then(()=>rpc('recover_casino_player_profile',{p_player_code:String(values.get('playerCode')).trim().toUpperCase(),p_recovery_key:String(values.get('recoveryKey')).trim().toUpperCase()})).then(loadDashboard).catch(error=>message(error.message||String(error)))};
  $('refreshAdmin').onclick=()=>loadDashboard().catch(error=>alert(error.message||String(error)));$('roomFilter').onchange=renderRooms;$('withdrawalFilter').onchange=renderWithdrawals;$('playerSearch').oninput=renderPlayers;$('closeActivity').onclick=()=>$('playerActivityPanel').hidden=true;$('closeRoomAdmin').onclick=()=>$('roomAdminPanel').hidden=true;
  loadDashboard().catch(()=>message('Introduce las credenciales del perfil administrador.'));
})();
