(function(){
  'use strict';
  const $=id=>document.getElementById(id),config=window.CASINO_SUPABASE_CONFIG||{};let client,rooms=[],players=[];
  const labels={blackjack:'Blackjack',roulette:'Ruleta','tres-y-dos':'Tres y Dos',domino:'Dominó',waiting:'Esperando',active:'Activa',closed:'Cerrada'};
  function message(text){$('adminMessage').textContent=text}
  function loadLibrary(){if(window.supabase?.createClient)return Promise.resolve();return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';script.onload=resolve;script.onerror=()=>reject(new Error('No se pudo cargar Supabase.'));document.head.appendChild(script)})}
  async function ensureClient(){if(client)return client;if(!config.url||!config.publishableKey)throw new Error('Supabase no está configurado.');await loadLibrary();client=window.supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});const {data:{session}}=await client.auth.getSession();if(!session){const {error}=await client.auth.signInAnonymously();if(error)throw error}return client}
  async function rpc(name,params){await ensureClient();const {data,error}=await client.rpc(name,params);if(error)throw error;return data}
  const format=value=>Number(value||0).toLocaleString('es-ES'),date=value=>new Date(value).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'});
  function cell(row,text,sub=''){const td=document.createElement('td'),strong=document.createElement('strong');strong.textContent=text;td.append(strong);if(sub){const small=document.createElement('small');small.textContent=sub;td.append(small)}row.append(td)}
  function renderSummary(summary){const cards=[['JUGADORES',summary.players,'perfiles'],['PUNTOS',summary.total_points,'acumulados'],['SALAS',summary.rooms,'creadas'],['ESPERANDO',summary.waiting_rooms,'salas'],['ACTIVAS',summary.active_rooms,'salas'],['CONECTADOS',summary.connected_members,'miembros']];$('summaryCards').replaceChildren(...cards.map(([label,value,sub])=>{const card=document.createElement('article');card.className='summary-card';const span=document.createElement('span'),b=document.createElement('b'),small=document.createElement('small');span.textContent=label;b.textContent=format(value);small.textContent=sub;card.append(span,b,small);return card}))}
  function renderRooms(){const filter=$('roomFilter').value,items=rooms.filter(room=>!filter||room.status===filter),body=$('roomsTable');if(!items.length){const row=document.createElement('tr'),td=document.createElement('td');td.colSpan=6;td.className='empty-row';td.textContent='No hay salas con este filtro.';row.append(td);body.replaceChildren(row);return}body.replaceChildren(...items.map(room=>{const row=document.createElement('tr');cell(row,room.invite_code,room.room_id);cell(row,labels[room.game_type]||room.game_type);const status=document.createElement('td'),pill=document.createElement('span');pill.className=`status-pill ${room.status}`;pill.textContent=labels[room.status]||room.status;status.append(pill);row.append(status);cell(row,room.host_name,room.host_mode==='moderator'?'Solo moderador':'Jugador y administrador');cell(row,String(room.member_count));cell(row,date(room.created_at));return row}))}
  function renderPlayers(){const query=$('playerSearch').value.trim().toLowerCase(),items=players.filter(player=>!query||player.display_name.toLowerCase().includes(query)||player.player_code.toLowerCase().includes(query)),body=$('playersTable');if(!items.length){const row=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.className='empty-row';td.textContent='No hay jugadores con este filtro.';row.append(td);body.replaceChildren(row);return}body.replaceChildren(...items.map(player=>{const row=document.createElement('tr');cell(row,player.display_name,player.player_code);cell(row,format(player.points));cell(row,player.room_code||'Sin sala',player.game_type?labels[player.game_type]||player.game_type:'');cell(row,player.room_credits===null?'—':format(player.room_credits));cell(row,date(player.created_at));return row}))}
  async function loadDashboard(){message('Verificando acceso…');const [summary,roomData,playerData]=await Promise.all([rpc('admin_casino_summary'),rpc('admin_list_casino_rooms'),rpc('admin_list_casino_players')]);rooms=roomData||[];players=playerData||[];renderSummary(summary);renderRooms();renderPlayers();$('adminLogin').hidden=true;$('adminDashboard').hidden=false;message('')}
  $('adminLoginForm').onsubmit=event=>{event.preventDefault();message('Recuperando perfil…');const values=new FormData(event.currentTarget);ensureClient().then(()=>rpc('recover_casino_player_profile',{p_player_code:String(values.get('playerCode')).trim().toUpperCase(),p_recovery_key:String(values.get('recoveryKey')).trim().toUpperCase()})).then(loadDashboard).catch(error=>message(error.message||String(error)))};
  $('refreshAdmin').onclick=()=>loadDashboard().catch(error=>alert(error.message||String(error)));$('roomFilter').onchange=renderRooms;$('playerSearch').oninput=renderPlayers;
  loadDashboard().catch(()=>message('Introduce las credenciales del perfil administrador.'));
})();
