(function(){
  'use strict';
  const $=id=>document.getElementById(id),KEY='casino.domino.v1';let botTimer,pending=null;
  let config;try{config=JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){config=null}
  if(!config)config={mode:'partners',target:100,players:Array.from({length:4},(_,i)=>({name:i?`Bot ${i}`:'Jugador 1',type:i?'bot':'human'}))};
  let state={phase:'setup',players:[],chain:[],left:null,right:null,current:0,passes:0,scores:{team0:0,team1:0,p0:0,p1:0,p2:0,p3:0},round:0,message:'Configura la mesa'};
  function save(){localStorage.setItem(KEY,JSON.stringify(config))}
  function setup(){
    $('dominoMode').value=config.mode;$('targetScore').value=String(config.target);
    $('dominoSetup').replaceChildren(...config.players.map((p,i)=>{const row=document.createElement('div');row.className='participant-row domino-person';row.innerHTML=`<span>${i+1}</span><input maxlength="14"><select><option value="human">Persona</option><option value="bot">Bot</option></select><b>${config.mode==='partners'?`E${i%2+1}`:'IND'}</b>`;const input=row.querySelector('input'),select=row.querySelector('select');input.value=p.name;select.value=p.type;input.onchange=e=>{config.players[i].name=e.target.value.trim()||`Jugador ${i+1}`;save()};select.onchange=e=>{config.players[i].type=e.target.value;save()};return row}));
    updateRules();renderScores();
  }
  function makeTiles(){const tiles=[];for(let a=0;a<=6;a++)for(let b=a;b<=6;b++)tiles.push({a,b,id:`${a}-${b}`});for(let i=tiles.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[tiles[i],tiles[j]]=[tiles[j],tiles[i]]}return tiles}
  function startMatch(){config.mode=$('dominoMode').value;config.target=Number($('targetScore').value);save();state.scores={team0:0,team1:0,p0:0,p1:0,p2:0,p3:0};state.round=0;deal()}
  function deal(){const tiles=makeTiles();state.players=config.players.map((p,i)=>({...p,id:`p${i}`,hand:tiles.slice(i*7,i*7+7)}));state.chain=[];state.left=null;state.right=null;state.passes=0;state.phase='playing';state.round++;pending=null;let best={player:0,value:-1};state.players.forEach((p,i)=>p.hand.forEach(t=>{if(t.a===t.b&&t.a>best.value)best={player:i,value:t.a}}));state.current=best.player;state.openingDouble=best.value;state.message=`${state.players[state.current].name} abre con el doble ${best.value}.`;lockSetup(true);render();scheduleBot()}
  function legalEnds(tile){if(!state.chain.length)return tile.a===tile.b&&tile.a===state.openingDouble?['right']:[];const ends=[];if(tile.a===state.left||tile.b===state.left)ends.push('left');if(state.right!==state.left&&(tile.a===state.right||tile.b===state.right))ends.push('right');return ends}
  function playable(player){return player.hand.map((tile,index)=>({tile,index,ends:legalEnds(tile)})).filter(x=>x.ends.length)}
  function choose(index){if(state.phase!=='playing'||state.players[state.current].type==='bot')return;const tile=state.players[state.current].hand[index],ends=legalEnds(tile);if(!ends.length)return;if(ends.length>1){pending=index;$('pendingTile').replaceChildren(tileEl(tile,false,false));$('endChooser').hidden=false;state.message=`${state.players[state.current].name}: elige izquierda o derecha.`;$('dominoStatus').textContent=state.message;return}play(index,ends[0])}
  function orient(tile,end){if(end==='left')return tile.b===state.left?{...tile}:{...tile,a:tile.b,b:tile.a};return tile.a===state.right||!state.chain.length?{...tile}:{...tile,a:tile.b,b:tile.a}}
  function play(index,end){const p=state.players[state.current],tile=p.hand[index],placed=orient(tile,end);p.hand.splice(index,1);if(!state.chain.length){state.chain=[placed];state.left=placed.a;state.right=placed.b}else if(end==='left'){state.chain.unshift(placed);state.left=placed.a}else{state.chain.push(placed);state.right=placed.b}pending=null;$('pendingTile').replaceChildren();$('endChooser').hidden=true;state.passes=0;if(!p.hand.length)return finishRound(state.current,false);nextTurn();render();scheduleBot()}
  function pass(){if(state.phase!=='playing')return;const p=state.players[state.current];if(playable(p).length)return;state.passes++;state.message=`${p.name} pasa.`;if(state.passes>=4)return finishBlocked();nextTurn();render();scheduleBot()}
  function nextTurn(){state.current=(state.current+1)%4;state.message=`Turno de ${state.players[state.current].name}.`}
  function pipTotal(player){return player.hand.reduce((sum,t)=>sum+t.a+t.b,0)}
  function finishBlocked(){if(config.mode==='partners'){const totals=[pipTotal(state.players[0])+pipTotal(state.players[2]),pipTotal(state.players[1])+pipTotal(state.players[3])];if(totals[0]===totals[1])return closeRound('Tranca empatada. Nadie suma puntos.');const team=totals[0]<totals[1]?0:1,points=state.players.reduce((s,p)=>s+pipTotal(p),0);state.scores[`team${team}`]+=points;closeRound(`Tranca: Equipo ${team+1} gana ${points} puntos.`)}else{const totals=state.players.map(p=>pipTotal(p)),low=Math.min(...totals),winners=totals.map((v,i)=>v===low?i:-1).filter(i=>i>=0);if(winners.length>1)return closeRound('Tranca empatada. Nadie suma puntos.');const winner=winners[0],points=totals.reduce((s,v,i)=>s+(i===winner?0:v),0);state.scores[`p${winner}`]+=points;closeRound(`Tranca: ${state.players[winner].name} gana ${points} puntos.`)}}
  function finishRound(index){const points=state.players.reduce((sum,p,i)=>sum+((config.mode==='partners'||i!==index)?pipTotal(p):0),0);if(config.mode==='partners'){const team=index%2;state.scores[`team${team}`]+=points;closeRound(`Equipo ${team+1} domina y suma ${points} puntos.`)}else{state.scores[`p${index}`]+=points;closeRound(`${state.players[index].name} domina y suma ${points} puntos.`)}}
  function closeRound(message){state.phase='round-over';state.message=message;const winner=matchWinner();if(winner){state.phase='match-over';state.message+=` ¡${winner} gana la partida!`}$('endChooser').hidden=true;render()}
  function matchWinner(){if(config.mode==='partners'){for(let i=0;i<2;i++)if(state.scores[`team${i}`]>=config.target)return`Equipo ${i+1}`}else{for(let i=0;i<4;i++)if(state.scores[`p${i}`]>=config.target)return state.players[i].name}return null}
  function botMove(){const p=state.players[state.current];if(state.phase!=='playing'||p.type!=='bot')return;const options=playable(p);if(!options.length)return pass();options.sort((x,y)=>(y.tile.a+y.tile.b)-(x.tile.a+x.tile.b));const move=options[0];play(move.index,move.ends[0])}
  function half(n){let cells='';const spots={0:[],1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]}[n];for(let i=1;i<=9;i++)cells+=`<i class="${spots.includes(i)?'pip':''}"></i>`;return`<span class="domino-half">${cells}</span>`}
  function tileEl(tile,hidden=false,button=false,index=0,owner=-1){const el=document.createElement(button?'button':'div');el.className=`domino-tile-piece ${tile.a===tile.b?'is-double':''} ${hidden?'tile-back':''}`;el.innerHTML=hidden?'<b>◆</b>':`${half(tile.a)}${half(tile.b)}`;if(button){el.disabled=owner!==state.current||state.phase!=='playing'||!legalEnds(tile).length;el.onclick=()=>choose(index)}return el}
  function render(){clearTimeout(botTimer);$('dominoStatus').textContent=state.message;$('dominoModeLabel').textContent=config.mode==='partners'?'POR PAREJAS':'PINTINTÍN';$('dominoChain').replaceChildren(...state.chain.map(t=>tileEl(t)));const current=state.players[state.current];$('passTurn').disabled=state.phase!=='playing'||current?.type==='bot'||playable(current).length>0;$('startDomino').hidden=state.phase!=='setup';$('nextDominoRound').hidden=state.phase!=='round-over';$('nextDominoRound').textContent='SIGUIENTE MANO';
    $('dominoSeats').replaceChildren(...state.players.map((p,i)=>{const seat=document.createElement('article');seat.className=`domino-seat ${i===state.current&&state.phase==='playing'?'active':''} seat-${i}`;seat.innerHTML=`<header><span>${p.type==='bot'?'⚙':p.name[0]}</span><div><b>${p.name}</b><small>${config.mode==='partners'?`EQUIPO ${i%2+1}`:'PINTINTÍN'} · ${p.hand.length} fichas</small></div></header><div class="domino-hand"></div>`;const hide=p.type==='bot'&&state.phase==='playing';seat.querySelector('.domino-hand').append(...p.hand.map((t,n)=>tileEl(t,hide,!hide,n,i)));return seat}));renderScores()}
  function renderScores(){const box=$('scoreBoard');if(config.mode==='partners')box.innerHTML=`<div><span>Equipo 1</span><b>${state.scores.team0}</b><small>Jugadores 1 y 3</small></div><div><span>Equipo 2</span><b>${state.scores.team1}</b><small>Jugadores 2 y 4</small></div>`;else box.innerHTML=config.players.map((p,i)=>`<div><span>${p.name}</span><b>${state.scores[`p${i}`]}</b></div>`).join('')}
  function lockSetup(lock){$('dominoMode').disabled=lock;$('targetScore').disabled=lock;$('dominoSetup').querySelectorAll('input,select').forEach(e=>e.disabled=lock)}
  function updateRules(){$('dominoRules').textContent=config.mode==='partners'?'Dos parejas se sientan alternadas. Cada jugador recibe siete fichas. La pareja que domina o suma menos tantos en una tranca recibe los puntos de las fichas restantes.':'En Pintintín los cuatro jugadores compiten individualmente. Quien domina o conserva menos tantos en una tranca suma los puntos de los demás.'}
  function scheduleBot(){const p=state.players[state.current];if(p?.type==='bot'&&state.phase==='playing')botTimer=setTimeout(botMove,650)}
  $('dominoMode').onchange=e=>{config.mode=e.target.value;save();setup()};$('targetScore').onchange=e=>{config.target=Number(e.target.value);save()};$('startDomino').onclick=startMatch;$('passTurn').onclick=pass;$('nextDominoRound').onclick=deal;$('playLeft').onclick=()=>{if(pending!==null)play(pending,'left')};$('playRight').onclick=()=>{if(pending!==null)play(pending,'right')};$('resetDomino').onclick=()=>{state={...state,phase:'setup',players:[],chain:[],left:null,right:null,current:0,passes:0,scores:{team0:0,team1:0,p0:0,p1:0,p2:0,p3:0},round:0,message:'Configura la mesa'};lockSetup(false);setup();render()};
  setup();render();
})();
