(function(){'use strict';const $=id=>document.getElementById(id);let ctx=null,snapshot=null,pendingTile=null,busy=false;const css=document.createElement('link');css.rel='stylesheet';css.href='css/domino-online.css';document.head.appendChild(css);
function spots(n){const map={0:[],1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]}[n];let html='';for(let i=1;i<=9;i++)html+=`<i class="${map.includes(i)?'pip':''}"></i>`;return`<span class="domino-half">${html}</span>`}function tileEl(value,hidden=false,playable=false){const [a,b]=value.split('-').map(Number),el=document.createElement(playable?'button':'div');el.className=`domino-tile-piece ${a===b?'is-double':''} ${hidden?'tile-back':''} ${playable?'playable':''}`;el.innerHTML=hidden?'<b>◆</b>':spots(a)+spots(b);if(playable)el.onclick=()=>choose(value);return el}
function legal(value){const s=snapshot.state,[a,b]=value.split('-').map(Number);if(!s.chain?.length)return s.opening_required?(value==='6-6'?['right']:[]):['right'];const ends=[];if(a===Number(s.left)||b===Number(s.left))ends.push('left');if(a===Number(s.right)||b===Number(s.right))ends.push('right');return ends}async function call(name,params){if(busy)return;busy=true;try{await ctx.rpc(name,params)}catch(e){alert(e.message||String(e))}finally{busy=false;await refresh()}}
function choose(value){const ends=legal(value);if(!ends.length)return;if(ends.length===1)return call('play_online_domino',{p_room_id:ctx.room.id,p_tile:value,p_end:ends[0]});pendingTile=value;$('pendingTile').replaceChildren(tileEl(value));$('endChooser').hidden=false;$('dominoStatus').textContent='Elige el extremo para colocar la ficha.'}
function renderScores(s){const box=$('scoreBoard');if(s.mode==='partners')box.innerHTML=`<div><span>Equipo 1</span><b>${s.scores?.team0||0}</b><small>Asientos 1 y 3</small></div><div><span>Equipo 2</span><b>${s.scores?.team1||0}</b><small>Asientos 2 y 4</small></div>`;else box.innerHTML=[0,1,2,3].map(i=>`<div><span>Asiento ${i+1}</span><b>${s.scores?.[`p${i}`]||0}</b></div>`).join('')}
function render(){if(!snapshot)return;const s=snapshot.state||{},started=s.kind==='domino',myTurn=started&&s.phase==='playing'&&Number(s.current_seat)===Number(snapshot.seat);document.body.classList.add('domino-online-active');$('dominoModeLabel').textContent='ONLINE · '+(s.mode==='pintintin'?'PINTINTÍN':'PAREJAS');$('dominoStatus').textContent=started?(s.message||`Turno del asiento ${Number(s.current_seat)+1}`):'El anfitrión debe iniciar la partida online';$('dominoChain').replaceChildren(...(s.chain||[]).map(v=>tileEl(v)));$('dominoChain').classList.add('online-chain');const members=ctx.members.filter(m=>m.seat!==null);$('dominoSeats').replaceChildren(...[0,1,2,3].map(seatNo=>{const member=members.find(m=>m.seat===seatNo),own=seatNo===snapshot.seat,count=own?snapshot.hand.length:member?(member.hand_count||7):0,seat=document.createElement('article');seat.className=`domino-seat seat-${seatNo} ${Number(s.current_seat)===seatNo&&s.phase==='playing'?'active':''}`;seat.innerHTML=`<header><span>${own?'T':member?.display_name?.[0]||'?'}</span><div><b>${member?.display_name||`Asiento ${seatNo+1}`}</b><small>${own?'TU MANO · ':''}${count} fichas</small></div></header><div class="domino-hand"></div>`;const hand=seat.querySelector('.domino-hand');if(own)hand.append(...snapshot.hand.map(v=>tileEl(v,false,myTurn&&legal(v).length>0)));else for(let i=0;i<count;i++)hand.append(tileEl('0-0',true));return seat}));$('passTurn').disabled=!myTurn||snapshot.hand.some(v=>legal(v).length);$('startDomino').hidden=started||!ctx.host;$('startDomino').textContent='INICIAR PARTIDA ONLINE';$('nextDominoRound').hidden=s.phase!=='round-over'||!ctx.host;$('nextDominoRound').textContent='SIGUIENTE MANO ONLINE';$('dominoSetup').hidden=true;$('dominoMode').disabled=!ctx.host;$('targetScore').disabled=!ctx.host;$('resetDomino').hidden=true;renderScores(s)}
async function refresh(){if(!ctx)return;try{snapshot=await ctx.rpc('get_online_domino_state',{p_room_id:ctx.room.id});ctx.members.forEach(member=>member.hand_count=Number(snapshot.hand_counts?.[member.seat]||0));render()}catch(e){$('dominoStatus').textContent=e.message||String(e)}}
function activate(detail){if(detail.room?.game_type!=='domino'||detail.room?.status!=='active')return;ctx=detail;refresh()}
window.addEventListener('casino:online-room',e=>activate(e.detail));if(window.CasinoOnlineRoom)activate(window.CasinoOnlineRoom);
const local={start:$('startDomino').onclick,next:$('nextDominoRound').onclick,pass:$('passTurn').onclick,left:$('playLeft').onclick,right:$('playRight').onclick};$('startDomino').onclick=e=>ctx?call('start_online_domino',{p_room_id:ctx.room.id,p_mode:$('dominoMode').value,p_target:Number($('targetScore').value)}):local.start?.call(e.currentTarget,e);$('nextDominoRound').onclick=e=>ctx?call('start_online_domino',{p_room_id:ctx.room.id,p_mode:snapshot.state.mode,p_target:Number(snapshot.state.target)}):local.next?.call(e.currentTarget,e);$('passTurn').onclick=e=>ctx?call('pass_online_domino',{p_room_id:ctx.room.id}):local.pass?.call(e.currentTarget,e);$('playLeft').onclick=e=>{if(!ctx)return local.left?.call(e.currentTarget,e);if(pendingTile)call('play_online_domino',{p_room_id:ctx.room.id,p_tile:pendingTile,p_end:'left'});pendingTile=null;$('endChooser').hidden=true};$('playRight').onclick=e=>{if(!ctx)return local.right?.call(e.currentTarget,e);if(pendingTile)call('play_online_domino',{p_room_id:ctx.room.id,p_tile:pendingTile,p_end:'right'});pendingTile=null;$('endChooser').hidden=true};
})();
