(function(){
  'use strict';
  const $=id=>document.getElementById(id),KEY='casino.domino.v1';let botTimer,pending=null,draggedTile=null;
  let config;try{config=JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){config=null}
  if(!config)config={mode:'partners',target:100,players:Array.from({length:4},(_,i)=>({name:i?`Bot ${i}`:'Jugador 1',type:i?'bot':'human'}))};
  let state={phase:'setup',players:[],chain:[],left:null,right:null,current:0,passes:0,lastPlayer:null,pendingAllPass:null,pendingSinglePassBonus:null,nextStarter:null,bonusMessage:'',scoreHistory:[],scores:{team0:0,team1:0,p0:0,p1:0,p2:0,p3:0},closingScores:{team0:0,team1:0,p0:0,p1:0,p2:0,p3:0},round:0,message:'Configura la mesa'};
  function save(){localStorage.setItem(KEY,JSON.stringify(config))}
  function ensureHistoryPanel(){if($('dominoHistory'))return;const details=document.createElement('details');details.id='dominoHistory';details.className='domino-history';details.innerHTML='<summary>REGISTRO DE PUNTOS <span id="historyCount">0</span></summary><div id="historyList"></div>';$('scoreBoard').after(details)}
  function setup(){
    ensureHistoryPanel();
    $('dominoMode').value=config.mode;$('targetScore').value=String(config.target);
    $('dominoSetup').replaceChildren(...config.players.map((p,i)=>{const row=document.createElement('div');row.className='participant-row domino-person';row.innerHTML=`<span>${i+1}</span><input maxlength="14"><select><option value="human">Persona</option><option value="bot">Bot</option></select><b>${config.mode==='partners'?`E${i%2+1}`:'IND'}</b>`;const input=row.querySelector('input'),select=row.querySelector('select');input.value=p.name;select.value=p.type;input.onchange=e=>{config.players[i].name=e.target.value.trim()||`Jugador ${i+1}`;save()};select.onchange=e=>{config.players[i].type=e.target.value;save()};return row}));
    updateRules();renderScores();
  }
  function makeTiles(){const tiles=[];for(let a=0;a<=6;a++)for(let b=a;b<=6;b++)tiles.push({a,b,id:`${a}-${b}`});for(let i=tiles.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[tiles[i],tiles[j]]=[tiles[j],tiles[i]]}return tiles}
  function startMatch(){config.mode=$('dominoMode').value;config.target=Number($('targetScore').value);save();state.scores={team0:0,team1:0,p0:0,p1:0,p2:0,p3:0};state.closingScores={team0:0,team1:0,p0:0,p1:0,p2:0,p3:0};state.scoreHistory=[];state.round=0;state.nextStarter=null;deal()}
  function deal(){const tiles=makeTiles();state.players=config.players.map((p,i)=>({...p,id:`p${i}`,hand:tiles.slice(i*7,i*7+7)}));state.chain=[];state.left=null;state.right=null;state.passes=0;state.lastPlayer=null;state.pendingAllPass=null;state.pendingSinglePassBonus=null;state.bonusMessage='';state.phase='playing';state.round++;pending=null;if(!state.closingScores)state.closingScores={...state.scores};if(state.round===1){const starter=state.players.findIndex(p=>p.hand.some(t=>t.a===6&&t.b===6));state.current=starter;state.openingTile='6-6';state.message=`${state.players[starter].name} inicia la partida con el doble 6.`}else{state.current=state.nextStarter??0;state.openingTile=null;state.message=`${state.players[state.current].name}, ganador de la mano anterior, realiza la salida.`}lockSetup(true);render();scheduleBot()}
  function legalEnds(tile){if(!state.chain.length)return state.openingTile?(tile.id===state.openingTile?['right']:[]):['right'];const ends=[];if(tile.a===state.left||tile.b===state.left)ends.push('left');if(tile.a===state.right||tile.b===state.right)ends.push('right');return ends}
  function playable(player){return player.hand.map((tile,index)=>({tile,index,ends:legalEnds(tile)})).filter(x=>x.ends.length)}
  function choose(index){if(state.phase!=='playing'||state.players[state.current].type==='bot')return;const tile=state.players[state.current].hand[index],ends=legalEnds(tile);if(!ends.length)return;if(ends.length>1){pending=index;$('pendingTile').replaceChildren(tileEl(tile,false,false));$('endChooser').hidden=false;state.message=`${state.players[state.current].name}: elige izquierda o derecha.`;$('dominoStatus').textContent=state.message;return}play(index,ends[0])}
  function orient(tile,end){if(end==='left')return tile.b===state.left?{...tile}:{...tile,a:tile.b,b:tile.a};return tile.a===state.right||!state.chain.length?{...tile}:{...tile,a:tile.b,b:tile.a}}
  function recordPoints(index,points,reason){const recipient=config.mode==='partners'?`Equipo ${index%2+1}`:state.players[index].name;state.scoreHistory.push({round:state.round,recipient,points,reason})}
  function scoreKey(index){return config.mode==='partners'?`team${index%2}`:`p${index}`}
  function addScore(index,points,reason,canClose=true){const key=scoreKey(index),before=state.scores[key]||0;if(!canClose&&points>0&&before+points>=config.target){recordPoints(index,0,`${reason} descartado por sobrepaso`);return false}state.scores[key]=Math.max(0,before+points);if(canClose){if(!state.closingScores)state.closingScores={...state.scores,[key]:before};state.closingScores[key]=(state.closingScores[key]||0)+points}recordPoints(index,points,reason);return true}
  function awardBonus(index,label,canClose=false){const applied=addScore(index,25,label,canClose);const notice=applied?`${label.toUpperCase()} · ${state.players[index].name} gana 25 puntos${canClose?'':' (no cierran la partida)'}`:`${label.toUpperCase()} · ${state.players[index].name} no suma 25 porque sobrepasa la meta`;state.bonusMessage=state.bonusMessage?`${state.bonusMessage} · ${notice}`:notice;return applied}
  function revokeBonus(index,label){addScore(index,-25,label,false);const notice=`${label.toUpperCase()} · se anulan 25 puntos de ${state.players[index].name}`;state.bonusMessage=state.bonusMessage?`${state.bonusMessage} · ${notice}`:notice}
  function settleSinglePassOnPlay(){state.pendingSinglePassBonus=null}
  function openSinglePassBonus(owner){state.pendingSinglePassBonus={owner,next:(owner+1)%4,awarded:false,cancel:(owner+2)%4}}
  function handleSinglePassOnPass(seat){const pendingBonus=state.pendingSinglePassBonus;if(!pendingBonus)return;if(!pendingBonus.awarded&&pendingBonus.next===seat){const applied=awardBonus(pendingBonus.owner,'Pase inmediato',false);if(applied)pendingBonus.awarded=true;else state.pendingSinglePassBonus=null;return}if(pendingBonus.awarded&&pendingBonus.cancel===seat){revokeBonus(pendingBonus.owner,'Anulación de pase inmediato');state.pendingSinglePassBonus=null}}
  function play(index,end){const p=state.players[state.current],tile=p.hand[index],capicua=p.hand.length===1&&tile.a!==tile.b&&state.chain.length>0&&legalEnds(tile).length===2,placed=orient(tile,end),completedAllPass=state.pendingAllPass===state.current;settleSinglePassOnPlay();placed.justPlaced=true;p.hand.splice(index,1);if(completedAllPass){awardBonus(state.current,'Pase a todos',false);state.pendingAllPass=null}if(!state.chain.length){placed.isOpening=true;state.chain=[placed];state.left=placed.a;state.right=placed.b}else if(end==='left'){state.chain.unshift(placed);state.left=placed.a}else{state.chain.push(placed);state.right=placed.b}pending=null;$('pendingTile').replaceChildren();$('endChooser').hidden=true;state.passes=0;state.lastPlayer=state.current;if(!p.hand.length){if(capicua)awardBonus(state.current,'Capicúa',true);return finishRound(state.current,capicua?' Capicúa: 25 puntos adicionales.':'')}openSinglePassBonus(state.current);nextTurn();render();scheduleBot()}
  function pass(){if(state.phase!=='playing')return;const p=state.players[state.current];if(playable(p).length)return;handleSinglePassOnPass(state.current);state.passes++;if(state.passes>=4){state.pendingAllPass=null;state.pendingSinglePassBonus=null;return finishBlocked()}nextTurn();if(state.passes===3&&state.current===state.lastPlayer){state.pendingAllPass=state.lastPlayer;state.message=`Los otros tres jugadores pasaron. ${state.players[state.lastPlayer].name} solo gana 25 puntos si puede jugar ahora.`}else state.message=`${p.name} pasa. Turno de ${state.players[state.current].name}.`;render();scheduleBot()}
  function nextTurn(){state.current=(state.current+1)%4;state.message=`Turno de ${state.players[state.current].name}.`}
  function pipTotal(player){return player.hand.reduce((sum,t)=>sum+t.a+t.b,0)}
  function finishBlocked(){const blocker=state.lastPlayer;if(config.mode==='pintintin'){const totals=state.players.map(pipTotal),lowest=Math.min(...totals),winners=totals.map((total,index)=>total===lowest?index:-1).filter(index=>index>=0);if(winners.length>1)return closeRound(`Tranca de Pintintín empatada con ${lowest} puntos. Nadie suma.`,blocker);const winner=winners[0],points=totals.reduce((sum,total)=>sum+total,0);addScore(winner,points,'Tranca de Pintintín',true);return closeRound(`Tranca de Pintintín: ${state.players[winner].name} tiene la menor mano (${lowest}) y suma los ${points} puntos de todas las fichas.`,winner)}const next=(blocker+1)%4,blockerPips=pipTotal(state.players[blocker]),nextPips=pipTotal(state.players[next]);if(blockerPips===nextPips)return closeRound(`Tranca empatada entre ${state.players[blocker].name} y ${state.players[next].name}: ${blockerPips} puntos. Nadie suma.`,blocker);const winner=blockerPips<nextPips?blocker:next,points=state.players.reduce((sum,p)=>sum+pipTotal(p),0);addScore(winner,points,'Tranca de frente',true);closeRound(`Tranca de frente: ${state.players[winner].name} tiene menos puntos (${Math.min(blockerPips,nextPips)} contra ${Math.max(blockerPips,nextPips)}) y su equipo suma los ${points} puntos de todas las fichas.`,winner)}
  function finishRound(index,special=''){const points=state.players.reduce((sum,p,i)=>sum+((config.mode==='partners'||i!==index)?pipTotal(p):0),0);addScore(index,points,'Dominó',true);if(config.mode==='partners'){const team=index%2;closeRound(`Equipo ${team+1} domina y suma ${points} puntos.${special}`,index)}else closeRound(`${state.players[index].name} domina y suma ${points} puntos.${special}`,index)}
  function closeRound(message,winnerIndex){state.phase='round-over';state.nextStarter=winnerIndex;state.message=message;const winner=matchWinner();if(winner){state.phase='match-over';state.message+=` ¡${winner} gana la partida al alcanzar la meta!`}else state.message+=` ${state.players[winnerIndex].name} saldrá en la próxima mano.`;$('endChooser').hidden=true;render()}
  function matchWinner(){const closing=state.closingScores||state.scores;if(config.mode==='partners'){for(let i=0;i<2;i++)if((closing[`team${i}`]||0)>=config.target)return`Equipo ${i+1}`}else{for(let i=0;i<4;i++)if((closing[`p${i}`]||0)>=config.target)return state.players[i].name}return null}
  function botMove(){const p=state.players[state.current];if(state.phase!=='playing'||p.type!=='bot')return;const options=playable(p);if(!options.length)return pass();options.sort((x,y)=>(y.tile.a+y.tile.b)-(x.tile.a+x.tile.b));const move=options[0];play(move.index,move.ends[0])}
  function half(n){let cells='';const spots={0:[],1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]}[n];for(let i=1;i<=9;i++)cells+=`<i class="${spots.includes(i)?'pip':''}"></i>`;return`<span class="domino-half">${cells}</span>`}
  function reorderHand(owner,from,to){if(from===to||from<0||to<0)return;const hand=state.players[owner].hand,[tile]=hand.splice(from,1);hand.splice(to,0,tile);render();scheduleBot()}
  function tileEl(tile,hidden=false,button=false,index=0,owner=-1){const el=document.createElement(button?'button':'div');el.className=`domino-tile-piece ${tile.a===tile.b?'is-double':''} ${hidden?'tile-back':''}`;el.innerHTML=hidden?'<b>◆</b>':`${half(tile.a)}${half(tile.b)}`;if(button){let wasDragged=false;const human=state.players[owner]?.type==='human',canPlay=owner===state.current&&state.phase==='playing'&&legalEnds(tile).length>0;el.disabled=hidden;el.classList.toggle('playable',canPlay);el.classList.toggle('not-playable',!canPlay);el.setAttribute('aria-disabled',String(!canPlay));el.onclick=()=>{if(canPlay&&!wasDragged)choose(index)};el.draggable=human&&state.phase==='playing';el.ondragstart=event=>{wasDragged=true;draggedTile={owner,index};el.classList.add('dragging');event.dataTransfer.effectAllowed='move'};el.ondragover=event=>{if(draggedTile?.owner===owner){event.preventDefault();event.dataTransfer.dropEffect='move'}};el.ondrop=event=>{event.preventDefault();if(draggedTile?.owner===owner)reorderHand(owner,draggedTile.index,index)};el.ondragend=()=>{draggedTile=null;el.classList.remove('dragging');setTimeout(()=>{wasDragged=false},0)}}return el}
  function pathTile(tile,arm,position){const shown=position.flip?{...tile,a:tile.b,b:tile.a}:tile,el=tileEl(shown);el.classList.add('domino-path-tile',`path-${arm}`);if(position.turn)el.classList.add('path-turn');if(tile.justPlaced)el.classList.add('newly-placed');el.style.setProperty('--path-x',`${position.x}px`);el.style.setProperty('--path-y',`${position.y}px`);return el}
  function buildArm(tiles,arm,openingWidth){const side=arm==='right'?1:-1,vertical=arm==='right'?1:-1,result=[],width=tile=>tile.a===tile.b?36:68;let cursor=side*(openingWidth/2);tiles.forEach((tile,index)=>{const tileWidth=width(tile);if(index<4){cursor+=side*(tileWidth/2);result.push(pathTile(tile,arm,{x:cursor,y:0,turn:false,flip:false}));cursor+=side*(tileWidth/2);return}const step=index-4,place=step%9,band=Math.floor(step/9),direction=side*(band%2===0?-1:1),baseY=52+band*104;if(place===0){result.push(pathTile(tile,arm,{x:cursor,y:vertical*baseY,turn:true,flip:false}));return}cursor+=direction*(tileWidth/2);result.push(pathTile(tile,arm,{x:cursor,y:vertical*(baseY+52),turn:false,flip:direction!==side}));cursor+=direction*(tileWidth/2)});return result}
  function renderChain(){const chain=$('dominoChain');if(!state.chain.length){chain.replaceChildren();return}const openingIndex=state.chain.findIndex(tile=>tile.isOpening),center=openingIndex>=0?openingIndex:Math.floor(state.chain.length/2),openingTile=state.chain[center],layout=document.createElement('div'),opening=tileEl(openingTile);layout.className='domino-path-layout';opening.classList.add('domino-path-tile','path-opening');if(openingTile.justPlaced)opening.classList.add('newly-placed');opening.style.setProperty('--path-x','0px');opening.style.setProperty('--path-y','0px');const left=state.chain.slice(0,center).reverse(),right=state.chain.slice(center+1),openingWidth=openingTile.a===openingTile.b?36:68;layout.append(opening,...buildArm(left,'left',openingWidth),...buildArm(right,'right',openingWidth));chain.replaceChildren(layout);state.chain.forEach(tile=>delete tile.justPlaced)}
  function render(){clearTimeout(botTimer);$('dominoStatus').textContent=state.message;$('dominoModeLabel').textContent=config.mode==='partners'?'POR PAREJAS':'PINTINTÍN';$('dominoBonus').textContent=state.bonusMessage;$('dominoBonus').hidden=!state.bonusMessage;renderChain();const current=state.players[state.current];$('passTurn').disabled=state.phase!=='playing'||current?.type==='bot'||playable(current).length>0;$('startDomino').hidden=state.phase!=='setup';$('nextDominoRound').hidden=state.phase!=='round-over';$('nextDominoRound').textContent='SIGUIENTE MANO';
    $('dominoSeats').replaceChildren(...state.players.map((p,i)=>{const seat=document.createElement('article');seat.className=`domino-seat ${i===state.current&&state.phase==='playing'?'active':''} seat-${i}`;seat.innerHTML=`<header><span>${p.type==='bot'?'⚙':p.name[0]}</span><div><b>${p.name}</b><small>${config.mode==='partners'?`EQUIPO ${i%2+1}`:'PINTINTÍN'} · ${p.hand.length} fichas</small></div></header><div class="domino-hand"></div>`;const hide=p.type==='bot'&&state.phase==='playing';seat.querySelector('.domino-hand').append(...p.hand.map((t,n)=>tileEl(t,hide,!hide,n,i)));return seat}));renderScores()}
  function renderHistory(){const list=$('historyList'),count=$('historyCount');if(!list||!count)return;count.textContent=String(state.scoreHistory.length);if(!state.scoreHistory.length){const empty=document.createElement('p');empty.textContent='Aún no se han anotado puntos.';list.replaceChildren(empty);return}list.replaceChildren(...state.scoreHistory.slice().reverse().map(entry=>{const row=document.createElement('div'),label=document.createElement('span'),points=document.createElement('strong'),recipient=document.createElement('small');label.textContent=`Mano ${entry.round} · ${entry.reason}`;points.textContent=entry.points>=0?`+${entry.points}`:`${entry.points}`;recipient.textContent=entry.recipient;row.append(label,points,recipient);return row}))}
  function renderScores(){const box=$('scoreBoard');if(config.mode==='partners')box.innerHTML=`<div><span>Equipo 1</span><b>${state.scores.team0}</b><small>Jugadores 1 y 3</small></div><div><span>Equipo 2</span><b>${state.scores.team1}</b><small>Jugadores 2 y 4</small></div>`;else box.innerHTML=config.players.map((p,i)=>`<div><span>${p.name}</span><b>${state.scores[`p${i}`]}</b></div>`).join('');renderHistory()}
  function lockSetup(lock){$('dominoMode').disabled=lock;$('targetScore').disabled=lock;$('dominoSetup').querySelectorAll('input,select').forEach(e=>e.disabled=lock)}
  function updateRules(){const scoring=config.mode==='partners'?'Los jugadores se sientan por parejas alternadas. En una tranca se comparan el trancador y el jugador siguiente.':'En Pintintín los cuatro jugadores compiten individualmente. En una tranca gana quien tenga menos puntos entre los cuatro.';$('dominoRules').textContent=`${scoring} Al resolver una tranca, se suman los puntos de todas las fichas restantes, incluidas las del ganador, y el total completo se acredita al ganador o a su equipo. La primera mano comienza obligatoriamente con el doble 6. Después, el ganador de cada mano realiza la salida siguiente hasta alcanzar la meta. Si un jugador coloca una ficha y el siguiente pasa, gana 25 puntos de pase inmediato; si el jugador que sigue también pasa, esos 25 se anulan. Hacer pasar a los otros tres jugadores vale 25 puntos solamente si quien los hizo pasar puede jugar al regresar su turno; si tampoco puede jugar, es una tranca y no recibe esos 25 puntos. Los 25 por pase inmediato y pase redondo no sirven para cerrar la partida ni para sobrepasar la meta; si no aplican, se descartan y no se suman al marcador. Terminar con una ficha no doble que podía jugarse en ambos extremos es capicúa y vale 25 puntos adicionales; la capicúa sí puede cerrar la partida. Los dobles nunca califican como capicúa.`}
  function scheduleBot(){const p=state.players[state.current];if(p?.type==='bot'&&state.phase==='playing')botTimer=setTimeout(botMove,650)}
  $('dominoMode').onchange=e=>{config.mode=e.target.value;save();setup()};$('targetScore').onchange=e=>{config.target=Number(e.target.value);save()};$('startDomino').onclick=startMatch;$('passTurn').onclick=pass;$('nextDominoRound').onclick=deal;$('playLeft').onclick=()=>{if(pending!==null)play(pending,'left')};$('playRight').onclick=()=>{if(pending!==null)play(pending,'right')};$('resetDomino').onclick=()=>{state={...state,phase:'setup',players:[],chain:[],left:null,right:null,current:0,passes:0,lastPlayer:null,pendingAllPass:null,pendingSinglePassBonus:null,nextStarter:null,bonusMessage:'',scoreHistory:[],scores:{team0:0,team1:0,p0:0,p1:0,p2:0,p3:0},closingScores:{team0:0,team1:0,p0:0,p1:0,p2:0,p3:0},round:0,message:'Configura la mesa'};lockSetup(false);setup();render()};
  setup();render();
})();
