(function(){'use strict';const $=id=>document.getElementById(id),config=window.CASINO_SUPABASE_CONFIG||{};let client;if(!document.querySelector('script[src="js/access-gate.js"]')){document.documentElement.classList.add('casino-access-pending');const style=document.createElement('link');style.rel='stylesheet';style.href='css/access-gate.css';document.head.appendChild(style);const gate=document.createElement('script');gate.src='js/access-gate.js';document.head.appendChild(gate)}
function message(text){$('profileMessage').textContent=text}function library(){if(window.supabase?.createClient)return Promise.resolve();return new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=ok;s.onerror=()=>no(new Error('No se pudo cargar Supabase'));document.head.append(s)})}
async function ensure(){if(client)return client;await library();client=window.supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});const {data:{session}}=await client.auth.getSession();if(!session){const {error}=await client.auth.signInAnonymously();if(error)throw error}return client}async function rpc(name,params){await ensure();const {data,error}=await client.rpc(name,params);if(error)throw error;return data}const fmt=n=>Number(n||0).toLocaleString('es-ES'),when=v=>new Date(v).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'});
function empty(body,cols,text){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=cols;td.className='empty-row';td.textContent=text;tr.append(td);body.replaceChildren(tr)}function td(row,text,cls=''){const cell=document.createElement('td');cell.textContent=text;if(cls)cell.className=cls;row.append(cell)}
function summary(data){$('profileName').textContent=data.display_name;$('profileCode').textContent=data.player_code;const cards=[['PUNTOS',data.points],['TRANSACCIONES',data.transactions],['PARTIDAS',data.games],['RETIROS PENDIENTES',data.pending_withdrawals],['NOTIFICACIONES',data.unread_notifications]];$('profileSummary').replaceChildren(...cards.map(([label,value])=>{const a=document.createElement('article');a.className='summary-card';const s=document.createElement('span'),b=document.createElement('b');s.textContent=label;b.textContent=fmt(value);a.append(s,b);return a}))}
function transactions(items){const body=$('transactionsTable');if(!items.length)return empty(body,4,'Todavía no hay transacciones.');body.replaceChildren(...items.map(x=>{const row=document.createElement('tr');td(row,when(x.created_at));td(row,x.description);td(row,`${x.amount>0?'+':''}${fmt(x.amount)}`,x.amount>=0?'positive':'negative');td(row,fmt(x.balance_after));return row}))}
function games(items){const body=$('gamesTable');if(!items.length)return empty(body,5,'El historial aparecerá cuando las partidas online registren resultados.');body.replaceChildren(...items.map(x=>{const row=document.createElement('tr');td(row,when(x.created_at));td(row,x.game_type);td(row,x.room_code||'—');td(row,x.result);td(row,`${x.points_delta>0?'+':''}${fmt(x.points_delta)}`,x.points_delta>=0?'positive':'negative');return row}))}
function notifications(items){const box=$('profileNotifications');if(!items.length){const p=document.createElement('p');p.className='empty-row';p.textContent='No tienes notificaciones.';box.replaceChildren(p);return}box.replaceChildren(...items.map(x=>{const a=document.createElement('article');a.className=`activity-item ${x.is_read?'':'unread'}`;const d=document.createElement('div'),b=document.createElement('b'),p=document.createElement('small');b.textContent=x.title;p.textContent=`${x.message} · ${when(x.created_at)}`;d.append(b,p);a.append(d);if(!x.is_read){const button=document.createElement('button');button.textContent='MARCAR LEÍDA';button.onclick=()=>rpc('mark_casino_notification_read',{p_notification_id:x.id}).then(load);a.append(button)}return a}))}
async function load(){const [dash,tx,history,notes]=await Promise.all([rpc('get_my_profile_dashboard'),rpc('list_my_point_transactions'),rpc('list_my_game_history'),rpc('list_my_casino_notifications')]);summary(dash);transactions(tx||[]);games(history||[]);notifications(notes||[]);$('profileLogin').hidden=true;$('profileDashboard').hidden=false;message('')}
$('profileLoginForm').onsubmit=e=>{e.preventDefault();const v=new FormData(e.currentTarget);message('Recuperando…');rpc('recover_casino_player_profile',{p_player_code:String(v.get('playerCode')).trim().toUpperCase(),p_recovery_key:String(v.get('recoveryKey')).trim().toUpperCase()}).then(load).catch(err=>message(err.message||String(err)))};
$('withdrawalForm').onsubmit=e=>{e.preventDefault();const v=new FormData(e.currentTarget),points=Number(v.get('points'));if(!confirm(`¿Solicitar el retiro de ${fmt(points)} puntos ficticios?`))return;rpc('request_points_withdrawal',{p_points:points}).then(()=>{e.currentTarget.reset();return load()}).catch(err=>alert(err.message||String(err)))};$('refreshProfile').onclick=()=>load().catch(err=>alert(err.message||String(err)));load().catch(()=>message('Introduce tus credenciales para abrir el perfil.'));
})();
