(function(){'use strict';
 const RED=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
 const $=id=>document.getElementById(id); const grid=$('numberGrid'),outside=$('outsideBets'); let bets=[],history=[],currentRotation=0,spinning=false;
 const EUROPEAN=['0','32','15','19','4','21','2','25','17','34','6','27','13','36','11','30','8','23','10','5','24','16','33','1','20','14','31','9','22','18','29','7','28','12','35','3','26'];
 const AMERICAN=['0','28','9','26','30','11','7','20','32','17','5','22','34','15','3','24','36','13','1','00','27','10','25','29','12','8','19','31','18','6','21','33','16','4','23','35','14','2'];
 const odds={straight:35,split:17,street:11,corner:8,sixline:5,trio:11,firstfour:8,topline:6,dozen:2,column:2,red:1,black:1,even:1,odd:1,low:1,high:1};
 const names={straight:'Pleno',split:'Caballo',street:'Calle',corner:'Cuadro',sixline:'Seisena',trio:'Trío',firstfour:'Primeros cuatro',topline:'Línea americana',dozen:'Docena',column:'Columna',red:'Rojo',black:'Negro',even:'Par',odd:'Impar',low:'1–18',high:'19–36'};
 function chip(){return Number($('chipValue').value)}
 function color(n){if(n==='0'||n==='00')return'green';return RED.has(Number(n))?'red':'black'}
 function add(type,target,label){if(spinning)return;const amount=chip();if(total()+amount>CasinoStore.wallet)return message('Créditos insuficientes.');bets.push({type,target,amount,label:label||`${names[type]} ${Array.isArray(target)?target.join('-'):target}`});renderBets()}
 function total(){return bets.reduce((s,b)=>s+b.amount,0)}
 function wheelPockets(){return $('wheelMode').value==='american'?AMERICAN:EUROPEAN}
 function renderWheel(){const pockets=wheelPockets(),step=360/pockets.length,numbers=$('wheelNumbers'),rotor=$('wheelRotor'),wheel=$('wheel');wheel.classList.add('real-wheel');if(!$('wheelArt')){const img=document.createElement('img');img.id='wheelArt';img.className='wheel-art';img.src='assets/roulette-wheel-real.png?v=3';img.alt='Rueda de ruleta';rotor.prepend(img)}numbers.replaceChildren(...pockets.map((n,i)=>{const label=document.createElement('span');label.className=color(n);label.textContent=n;label.style.setProperty('--angle',`${i*step}deg`);return label}));const stops=pockets.map((n,i)=>{const start=i*step,end=(i+1)*step,shade=color(n)==='green'?'#178050':color(n)==='red'?'#b92d39':'#181b1a';return`${shade} ${start}deg ${end}deg`});rotor.style.background=`conic-gradient(from ${-step/2}deg,${stops.join(',')})`;rotor.style.transform=`rotate(${currentRotation}deg)`}
 function renderBoard(){const american=$('wheelMode').value==='american';const nums=[...(american?['0','00']:['0']),...Array.from({length:36},(_,i)=>String(i+1))];grid.replaceChildren(...nums.map(n=>{const b=document.createElement('button');b.className=`number-cell ${color(n)}`;b.textContent=n;b.addEventListener('click',()=>add('straight',[n]));return b}));renderWheel();
  const opts=[['low','1–18'],['even','PAR'],['red','ROJO'],['black','NEGRO'],['odd','IMPAR'],['high','19–36'],['dozen:1','1ª DOCENA'],['dozen:2','2ª DOCENA'],['dozen:3','3ª DOCENA'],['column:1','COLUMNA 1'],['column:2','COLUMNA 2'],['column:3','COLUMNA 3']];outside.replaceChildren(...opts.map(([key,label])=>{const [type,target]=key.split(':');const b=document.createElement('button');b.className=`outside-cell ${type}`;b.textContent=label;b.addEventListener('click',()=>add(type,target?Number(target):null,label));return b})) }
 function renderBets(){$('totalBet').textContent=`${total().toLocaleString('es-ES')} créditos`;$('betList').replaceChildren(...bets.map((b,i)=>{const row=document.createElement('div');row.innerHTML=`<span>${b.label}</span><b>${b.amount}</b><button aria-label="Quitar apuesta">×</button>`;row.querySelector('button').onclick=()=>{if(!spinning){bets.splice(i,1);renderBets()}};return row}))}
 function message(text){$('resultLabel').textContent=text}
 function parseTargets(){return $('betTarget').value.split(',').map(x=>x.trim()).filter(Boolean)}
 function valid(type,a){const mode=$('wheelMode').value;const nums=a.map(Number);if(type==='straight')return a.length===1&&validPocket(a[0],mode);if(type==='split'){if(a.length!==2||!a.every(x=>validPocket(x,mode)))return false;if(a.includes('0')||a.includes('00'))return a.some(x=>['1','2','3'].includes(x));return Math.abs(nums[0]-nums[1])===3||(Math.ceil(nums[0]/3)===Math.ceil(nums[1]/3)&&Math.abs(nums[0]-nums[1])===1)}if(type==='street')return a.length===3&&nums[0]%3===1&&nums[1]===nums[0]+1&&nums[2]===nums[0]+2;if(type==='corner')return a.length===4&&nums[0]%3!==0&&nums[1]===nums[0]+1&&nums[2]===nums[0]+3&&nums[3]===nums[0]+4;if(type==='sixline')return a.length===6&&nums[0]%3===1&&nums.every((n,i)=>n===nums[0]+i);if(type==='trio')return ['0,1,2','0,2,3','0,00,2','00,2,3'].includes(a.join(','));if(type==='firstfour')return mode==='european'&&a.join(',')==='0,1,2,3';if(type==='topline')return mode==='american'&&a.join(',')==='0,00,1,2,3';return false}
 function validPocket(x,mode){return x==='0'||(mode==='american'&&x==='00')||(Number.isInteger(Number(x))&&Number(x)>=1&&Number(x)<=36)}
 function wins(b,r){const n=Number(r);if(['straight','split','street','corner','sixline','trio','firstfour','topline'].includes(b.type))return b.target.includes(String(r));if(r==='0'||r==='00')return false;if(b.type==='red'||b.type==='black')return color(r)===b.type;if(b.type==='even')return n%2===0;if(b.type==='odd')return n%2===1;if(b.type==='low')return n<=18;if(b.type==='high')return n>=19;if(b.type==='dozen')return Math.ceil(n/12)===b.target;if(b.type==='column')return ((n-1)%3)+1===b.target;return false}
 function spin(){if(spinning)return;if(!bets.length)return message('Coloca al menos una apuesta.');const pockets=wheelPockets(),index=Math.floor(Math.random()*pockets.length),r=pockets[index],stake=total(),step=360/pockets.length,desired=-index*step,current=((currentRotation%360)+360)%360,delta=360*(7+Math.floor(Math.random()*3))+((desired-current+360)%360),wheel=$('wheel');spinning=true;$('spinBtn').disabled=true;$('wheelMode').disabled=true;wheel.style.setProperty('--ball-start',`${-45-Math.random()*90}deg`);wheel.style.setProperty('--ball-final',`${Math.random()*18-9}deg`);wheel.classList.add('is-spinning');message('La bola está girando…');currentRotation+=delta;requestAnimationFrame(()=>{$('wheelRotor').style.transform=`rotate(${currentRotation}deg)`});setTimeout(()=>{let returns=0;bets.forEach(b=>{if(wins(b,r))returns+=b.amount*(odds[b.type]+1)});CasinoStore.setWallet(CasinoStore.wallet-stake+returns);$('wheelResult').textContent=r;$('resultNumber').textContent=r;$('resultNumber').className=color(r);message(returns?`Cobras ${returns} créditos · resultado ${color(r)}`:`La casa gana · resultado ${color(r)}`);history.unshift(r);history=history.slice(0,10);$('history').innerHTML=history.map(x=>`<i class="${color(x)}">${x}</i>`).join('');bets=[];renderBets();spinning=false;$('spinBtn').disabled=false;$('wheelMode').disabled=false;wheel.classList.remove('is-spinning')},5300)}
 $('wheelMode').addEventListener('change',()=>{bets=[];currentRotation=0;renderBoard();renderBets()});$('clearBets').onclick=()=>{if(!spinning){bets=[];renderBets()}};$('spinBtn').onclick=spin;$('addAdvanced').onclick=()=>{const type=$('betType').value,target=parseTargets();if(!valid(type,target))return message('Esa combinación no es válida para este tipo de apuesta.');add(type,target)};renderBoard();renderBets();
})();
