(function(){
  'use strict';
  const pathCss=document.createElement('link');pathCss.rel='stylesheet';pathCss.href='css/domino-online-path.css';document.head.appendChild(pathCss);
  const pokerSeen=new Set(),pokerSlots=new Map();let onlineChain=[],onlineOpeningIndex=0,motionQueued=false,lastDominoTurn=null;
  const reducedMotion=()=>document.documentElement.classList.contains('reduce-motion')||document.body.classList.contains('reduce-motion')||matchMedia('(prefers-reduced-motion: reduce)').matches;
  function center(element){if(!element)return null;const rect=element.getBoundingClientRect();return rect.width||rect.height?{x:rect.left+rect.width/2,y:rect.top+rect.height/2}:null}
  function pokerDeck(){const felt=document.querySelector('.poker-felt');if(!felt)return null;let deck=document.getElementById('pokerMotionDeck');if(!deck){deck=document.createElement('div');deck.id='pokerMotionDeck';deck.className='motion-card-deck';deck.setAttribute('aria-hidden','true');deck.innerHTML='<i></i><i></i><i></i>';felt.appendChild(deck)}return deck}
  function cardSource(card){if(card.classList.contains('playing-card'))return document.querySelector('.shoe');if(card.classList.contains('tyd-card'))return document.querySelector('#drawStock .pile')||document.getElementById('drawStock');if(card.classList.contains('poker-card'))return pokerDeck();return null}
  function flyCard(card,index){if(card.dataset.motionFlown)return;card.dataset.motionFlown='true';card.classList.add('motion-flown');if(reducedMotion())return;const from=center(cardSource(card)),to=center(card);if(!from||!to)return;const dx=from.x-to.x,dy=from.y-to.y,rotation=Math.max(-18,Math.min(18,dx/28));card.animate([{translate:`${dx}px ${dy}px`,rotate:`${rotation}deg`,scale:.72,opacity:0,filter:'blur(2px)',offset:0},{translate:`${dx*.34}px ${dy*.28}px`,rotate:`${rotation*.28}deg`,scale:.9,opacity:.82,filter:'blur(.5px)',offset:.62},{translate:'-3px 5px',rotate:'-1deg',scale:1.035,opacity:1,filter:'blur(0)',offset:.86},{translate:'0 0',rotate:'0deg',scale:1,opacity:1,filter:'none',offset:1}],{duration:920,delay:Math.min(index,12)*95,easing:'cubic-bezier(.16,.78,.18,1)',fill:'both'})}
  function inferredDominoSeat(){const active=document.querySelector('.domino-seat.active');if(active){const match=active.className.match(/seat-(\d)/);if(match)return(Number(match[1])+3)%4}return lastDominoTurn}
  function dominoSource(tile){const seat=tile.dataset.originSeat??inferredDominoSeat();return seat!==null?document.querySelector(`.domino-seat.seat-${seat} .domino-hand`):null}
  function flyDomino(tile){if(tile.dataset.motionFlown)return;tile.dataset.motionFlown='true';tile.classList.add('motion-flown');if(reducedMotion())return;const from=center(dominoSource(tile)),to=center(tile);if(!from||!to)return;const dx=from.x-to.x,dy=from.y-to.y,rotation=tile.classList.contains('path-left')?-10:10;tile.animate([{translate:`${dx}px ${dy}px`,rotate:`${rotation}deg`,scale:.78,opacity:.18,filter:'blur(1.5px)',boxShadow:'0 25px 34px rgba(0,0,0,.18)',offset:0},{translate:`${dx*.3}px ${dy*.25}px`,rotate:`${rotation*.25}deg`,scale:.93,opacity:.9,filter:'blur(.3px)',boxShadow:'0 22px 28px rgba(0,0,0,.38)',offset:.68},{translate:'-2px -7px',rotate:'-1deg',scale:1.04,opacity:1,filter:'blur(0)',boxShadow:'0 20px 22px rgba(0,0,0,.55),0 0 18px rgba(244,194,70,.28)',offset:.86},{translate:'0 0',rotate:'0deg',scale:1,opacity:1,filter:'none',boxShadow:'0 2px 5px rgba(0,0,0,.5)',offset:1}],{duration:1050,easing:'cubic-bezier(.16,.76,.18,1)',fill:'both'})}
  const cardSignature=card=>card.textContent.trim()||'BACK';
  function scanPoker(){document.querySelectorAll('.poker-cards').forEach(container=>{const owner=container.closest('.poker-seat')?.querySelector('header b')?.textContent||'COMMUNITY';[...container.querySelectorAll('.poker-card')].forEach((card,index)=>{const slot=`${owner}:${index}`,signature=cardSignature(card),key=`${slot}:${signature}`,previous=pokerSlots.get(slot);card.style.setProperty('--motion-index',String(index));if(previous==='BACK'&&signature!=='BACK')card.classList.add('card-reveal');else if(!pokerSeen.has(key)){card.classList.add('fresh-card');pokerSeen.add(key)}pokerSlots.set(slot,signature)})})}
  const tileSignature=tile=>tile.dataset.dominoValue||[...tile.querySelectorAll('.domino-half')].map(half=>half.querySelectorAll('.pip').length).join('-');
  function positionOnlineTile(tile,arm,position,index){tile.dataset.dominoValue=tileSignature(tile);tile.dataset.chainIndex=String(index);tile.classList.add('domino-path-tile',`path-${arm}`);if(position.turn)tile.classList.add('path-turn');tile.style.setProperty('--path-x',`${position.x}px`);tile.style.setProperty('--path-y',`${position.y}px`);if(position.flip&&!tile.dataset.flipped){const halves=[...tile.querySelectorAll('.domino-half')];if(halves.length===2)tile.append(halves[1],halves[0]);tile.dataset.flipped='true'}return tile}
  function buildOnlineArm(entries,arm,openingWidth){const side=arm==='right'?1:-1,vertical=arm==='right'?1:-1,result=[],width=entry=>entry.tile.classList.contains('is-double')?36:68;let cursor=side*(openingWidth/2);entries.forEach((entry,index)=>{const tileWidth=width(entry);if(index<4){cursor+=side*(tileWidth/2);result.push(positionOnlineTile(entry.tile,arm,{x:cursor,y:0,turn:false,flip:false},entry.index));cursor+=side*(tileWidth/2);return}const step=index-4,place=step%9,band=Math.floor(step/9),direction=side*(band%2===0?-1:1),baseY=52+band*104;if(place===0){result.push(positionOnlineTile(entry.tile,arm,{x:cursor,y:vertical*baseY,turn:true,flip:false},entry.index));return}cursor+=direction*(tileWidth/2);result.push(positionOnlineTile(entry.tile,arm,{x:cursor,y:vertical*(baseY+52),turn:false,flip:direction!==side},entry.index));cursor+=direction*(tileWidth/2)});return result}
  function layoutOnlineDomino(){if(!document.body.classList.contains('domino-online-active'))return;const chain=document.getElementById('dominoChain');if(!chain||chain.querySelector(':scope > .domino-path-layout'))return;const tiles=[...chain.querySelectorAll(':scope > .domino-tile-piece')];if(!tiles.length)return;tiles.forEach(tile=>tile.dataset.dominoValue=tileSignature(tile));const values=tiles.map(tileSignature);if(values.length===1)onlineOpeningIndex=0;else if(!onlineChain.length)onlineOpeningIndex=Math.floor(values.length/2);else if(values.length===onlineChain.length+1&&values.slice(1).join('|')===onlineChain.join('|'))onlineOpeningIndex++;const center=Math.max(0,Math.min(tiles.length-1,onlineOpeningIndex)),opening=tiles[center],layout=document.createElement('div'),openingWidth=opening.classList.contains('is-double')?36:68;layout.className='domino-path-layout';chain.classList.add('has-path-layout');positionOnlineTile(opening,'opening',{x:0,y:0,turn:false,flip:false},center);opening.classList.add('path-opening');const left=tiles.slice(0,center).map((tile,index)=>({tile,index})).reverse(),right=tiles.slice(center+1).map((tile,index)=>({tile,index:index+center+1}));layout.append(opening,...buildOnlineArm(left,'left',openingWidth),...buildOnlineArm(right,'right',openingWidth));chain.replaceChildren(layout)}
  function scanOnlineDomino(){if(!document.body.classList.contains('domino-online-active'))return;layoutOnlineDomino();const chain=document.getElementById('dominoChain'),tiles=chain?[...chain.querySelectorAll('.domino-path-tile')].sort((a,b)=>Number(a.dataset.chainIndex)-Number(b.dataset.chainIndex)):[],next=tiles.map(tileSignature);if(!next.length)onlineOpeningIndex=0;let placed=-1,side='right';if(next.length===1&&!onlineChain.length)placed=0;else if(next.length===onlineChain.length+1){if(next.slice(1).join('|')===onlineChain.join('|')){placed=0;side='left'}else if(next.slice(0,-1).join('|')===onlineChain.join('|'))placed=next.length-1}if(placed>=0){const tile=tiles.find(item=>Number(item.dataset.chainIndex)===placed);tile?.classList.add('newly-placed',`path-${side}`);if(tile)tile.dataset.originSeat=document.body.dataset.dominoOriginSeat||String(inferredDominoSeat()??0)}onlineChain=next}
  function runMotions(){motionQueued=false;document.querySelectorAll('.fresh-card:not([data-motion-flown])').forEach((card,index)=>flyCard(card,index));document.querySelectorAll('.newly-placed:not([data-motion-flown])').forEach(flyDomino);const active=document.querySelector('.domino-seat.active');if(active){const match=active.className.match(/seat-(\d)/);if(match)lastDominoTurn=Number(match[1])}}
  function queueMotions(){if(motionQueued)return;motionQueued=true;requestAnimationFrame(()=>requestAnimationFrame(runMotions))}
  const observer=new MutationObserver(()=>{scanPoker();scanOnlineDomino();queueMotions()});
  function start(){pokerDeck();const poker=document.getElementById('pokerSeats'),community=document.getElementById('communityCards'),domino=document.getElementById('dominoChain');[document.getElementById('seats'),document.getElementById('dealerHand'),document.getElementById('tresSeats'),poker,community,domino].filter(Boolean).forEach(area=>observer.observe(area,{childList:true,subtree:true}));document.getElementById('startPoker')?.addEventListener('click',()=>{pokerSeen.clear();pokerSlots.clear()},{capture:true});scanPoker();scanOnlineDomino();queueMotions()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
